### ISSUE TITLE
Missing return

### ISSUE THREAD

**Issue by PanderMusubi** [hideakitai/ofxArtnetProtocol#2]
When using with OpenFrameworks 0.10.1, the following error arises:

    /home/pi/of_v0.10.1_linuxarmv6l_release/addons/ofxArtnetProtocol/src/ofxArtnetProtocol.cpp: In member function ‘uint16_t ofxArtnetProtocol::read()’:
    /home/pi/of_v0.10.1_linuxarmv6l_release/addons/ofxArtnetProtocol/src/ofxArtnetProtocol.cpp:106:1: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^

This can be solved by moving the latest return outside of the else clause.

**Comment by hideakitai** [comment]
I'm sorry for late reply.
This issue will be closed because I will archive this library and replace this with new Artnet library.
I will fix them in new one. Thank you for your information!
